name: Build and test on pull requests

on:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master
    with:
      JDK_VERSION: 25