name: Deploy tested project to GCP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    if: success() || failure()
    needs: [call-build, call-accept-before]
    with:
      gcp_project: 'trevorism-trade'
      gcp_project_id: '115921067586'
      version: '0-7-0'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

  call-accept-before:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  call-accept-after:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    needs: call-deploy
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
