name: Deploy tested project to GCP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, closed ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  id-token: write
  checks: write
  pull-requests: write

jobs:
  pipeline:
    uses: trevorism/actions-workflows/.github/workflows/pipeline.yml@master
    with:
      gcp_project: 'trevorism-trade'
      gcp_project_id: '115921067586'
      service: 'default'
    secrets: inherit
